export const GET_REVIEWS = 'GET_REVIEWS';
export const SET_REVIEW_FILTER = 'SET_REVIEW_FILTER';
export const SET_CATEGORY_FILTER = 'SET_CATEGORY_FILTER';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const SET_PAGE = 'SET_PAGE';
export const SET_LOADING = 'SET_LOADING';
